// Renders a PDF session report and streams it to an Express response.
//
// We use pdfkit (MIT, ~600 kB, no native deps) rather than a headless browser
// because it ships inside the same Node process — no Chrome download, no
// inter-process flakiness, and the result is deterministic for snapshot
// testing.

import PDFDocument from 'pdfkit';
import { prisma } from '../config/db.js';
import { getSession } from './session.service.js';
import { NotFound } from '../utils/errors.js';

const SUMMARY_PREFIX = 'summary.';

export async function streamSessionReport(userId, sessionId, res) {
  const session = await getSession(userId, sessionId);

  const [summaryRows, predictions, frameCount] = await Promise.all([
    prisma.metric.findMany({
      where: { sessionId, name: { startsWith: SUMMARY_PREFIX } },
      orderBy: { name: 'asc' },
    }),
    prisma.prediction.groupBy({
      by: ['kind', 'label'],
      where: { sessionId },
      _count: { _all: true },
      orderBy: { _count: { label: 'desc' } },
      take: 8,
    }),
    prisma.poseFrame.count({ where: { sessionId } }),
  ]);

  if (!session) throw NotFound('Session not found');

  const biomech = { rom: {}, symmetry: {}, gait: {} };
  for (const m of summaryRows) {
    const [, group, ...rest] = m.name.split('.');
    if (group in biomech) biomech[group][rest.join('.')] = m.value;
  }

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="session-${sessionId}.pdf"`);

  const doc = new PDFDocument({ size: 'A4', margin: 50, info: { Title: `SprintAI · ${session.label}` } });
  doc.pipe(res);

  // ---------- Header ----------
  doc.fontSize(24).fillColor('#1d4ed8').text('SprintAI Session Report');
  doc.moveDown(0.3);
  doc.fontSize(14).fillColor('#0f172a').text(session.label);
  doc.fontSize(10).fillColor('#475569')
    .text(`${new Date(session.startedAt).toLocaleString()} · ${session.source} · ${session.status}`);
  doc.moveDown(0.5);
  doc.strokeColor('#cbd5e1').lineWidth(1).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
  doc.moveDown();

  // ---------- Summary stats ----------
  section(doc, 'Capture summary');
  kv(doc, 'Total frames recorded', frameCount.toLocaleString());
  if (session.endedAt) {
    const dur = (new Date(session.endedAt) - new Date(session.startedAt)) / 1000;
    kv(doc, 'Duration', `${dur.toFixed(1)} s`);
  }

  // ---------- Biomech ----------
  if (Object.keys(biomech.rom).length || Object.keys(biomech.symmetry).length || biomech.gait.cadence_spm != null) {
    doc.moveDown(0.5);
    section(doc, 'Biomechanical metrics');
    for (const [joint, range] of Object.entries(biomech.rom)) {
      kv(doc, `ROM · ${joint}`, `${range.toFixed(1)}°`);
    }
    for (const [pair, idx] of Object.entries(biomech.symmetry)) {
      kv(doc, `Symmetry · ${pair} (lower is better)`, `${idx.toFixed(1)}%`);
    }
    if (biomech.gait.cadence_spm != null) {
      kv(doc, 'Cadence', `${biomech.gait.cadence_spm.toFixed(0)} steps/min`);
    }
  }

  // ---------- Predictions ----------
  if (predictions.length) {
    doc.moveDown(0.5);
    section(doc, 'Top predictions');
    for (const p of predictions) {
      kv(doc, `${p.kind.toLowerCase()}: ${p.label}`, `${p._count._all} frame(s)`);
    }
  }

  // ---------- Footer ----------
  doc.moveDown(1.5);
  doc.fontSize(8).fillColor('#94a3b8')
    .text('Generated by SprintAI — local, offline-capable biomechanics platform.', { align: 'center' });

  doc.end();
}

function section(doc, title) {
  doc.fontSize(14).fillColor('#1d4ed8').text(title);
  doc.moveDown(0.25);
  doc.fillColor('#0f172a').fontSize(11);
}

function kv(doc, key, value) {
  const y = doc.y;
  doc.fontSize(11).fillColor('#475569').text(key, 50, y, { width: 300 });
  doc.fillColor('#0f172a').text(String(value), 350, y, { width: 195, align: 'right' });
  doc.moveDown(0.25);
}
